services:
  temporal:
    build:
      context: .
      dockerfile: Dockerfile.temporal.dev
    command:
      - server
      - start-dev
      - --ip
      - 0.0.0.0
    ports:
      - "7233:7233"
      - "8233:8233"
